version: "3"

services:

  mariadb:
    image: mariadb:latest
    container_name: ami-stack-mariadb
    volumes:
      - ./data-mariadb/:/var/lib/mysql/:rw
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "660:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "661:80"

  mosquitto:
    image: amiteam/mosquitto:latest
    container_name: ami-stack-mosquitto
    volumes:
      - ./data-mosquitto/config/:/mosquitto/config/
      - ./data-mosquitto/data/:/mosquitto/data/
      - ./data-mosquitto/log/:/mosquitto/log/
    ports:
      - "662:1883"
      - "663:9001"

  ap:
    image: amiteam/pipeline:latest
    container_name: ami-stack-pipeline
    depends_on:
      - mosquitto
    volumes:
      - ./data-pipeline/:/data/
    ports:
      - "664:1880"

  aes:
    image: amiteam/exclusion-server:latest
    container_name: ami-stask-exclusion-server
    depends_on:
      - mosquitto
    volumes:
      - ./data-exclusion-server/logs/:/AMITaskServer/logs/
    environment:
      SERVER_NAME: EXCLUSION
      MQTT_URL: ws://mosquitto:9001/ws/
      MQTT_USERNAME: anonymous
      MQTT_PASSWORD: anonymous
    ports:
      - "665:1357"

  ats:
    image: amiteam/task-server:latest
    container_name: ami-stack-task-server
    depends_on:
      - aes
      - mariadb
      - mosquitto
    volumes:
      - ./data-task-server/logs/:/AMITaskServer/logs/
      - ./data-task-server/tasks/:/AMITaskServer/tasks/
    environment:
      SERVER_NAME: DEMO
      MQTT_URL: ws://mosquitto:9001/ws/
      MQTT_USERNAME: anonymous
      MQTT_PASSWORD: anonymous
      JDBC_URL: jdbc:mariadb://mariadb:3306/task?serverTimezone=UTC
      JDBC_USERNAME: root
      JDBC_PASSWORD: root
      EXCLUSION_SERVER_URL: http://aes:1357/

  as:
    image: amiteam/server:latest
    container_name: ami-stack-server
    depends_on:
      - mariadb
      - mosquitto
    volumes:
      - ./data-server/:/AMI/cmd/
    environment:
      BASE_URL: http://localhost:667/
      ADMIN_USER: admin
      ADMIN_PASS: demo
      ADMIN_EMAIL: ami@lpsc.in2p3.fr
      ENCRYPTION_KEY: BHbKwRM4lgHWJxFE
      AUTHORIZED_IPS: ""
      ROUTER_CATALOG: router
      ROUTER_SCHEMA: "@NULL"
      ROUTER_URL: jdbc:mariadb://mariadb:3306/router?serverTimezone=UTC
      ROUTER_USER: root
      ROUTER_PASS: root
    ports:
      - "666:8080"

  awf:
    image: amiteam/web-framework:latest
    container_name: ami-stack-web-framework
    volumes:
      - ./data-web-framework/:/usr/share/nginx/html/
    environment:
      AMI_HOME_PAGE_TITLE: Demo
      AMI_HOME_PAGE_ENDPOINT: http://localhost:666/AMI/FrontEnd
    ports:
      - "667:80"
    labels:
      kompose.service.type: LoadBalancer
